import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application.
    application
    kotlin("jvm") version "1.3.61"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit integration.
    testImplementation("org.junit.jupiter:junit-jupiter:5.6.0")

    // Use CraftBukkit blob.
    testImplementation("com.github.azbh111:craftbukkit-1.12.2:R")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.3.61")
}

application {
    // Define the main class for the application.
    // mainClassName =
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}